[package]
name = "pino_utils"
version = "0.1.0"
authors = ["pinosaur"]
description = "general rust utility functions and macros"
repository = "https://github.com/MrPicklePinosaur/pino_utils"
edition = "2021"

[dependencies]
enum_string = { path = "../enum_string" }
